version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - GRABADORA_REDIS_URL=redis://redis:6379/0
      - GRABADORA_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/grabadora
      - GRABADORA_S3_ENDPOINT_URL=http://minio:9000
      - GRABADORA_S3_ACCESS_KEY=minioadmin
      - GRABADORA_S3_SECRET_KEY=minioadmin
      - GRABADORA_S3_BUCKET_AUDIO=audio
      - GRABADORA_S3_BUCKET_TRANSCRIPTS=transcripts
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  worker:
    build: .
    command: python -m rq worker transcription --url redis://redis:6379/0
    environment:
      - GRABADORA_REDIS_URL=redis://redis:6379/0
      - GRABADORA_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/grabadora
      - GRABADORA_S3_ENDPOINT_URL=http://minio:9000
      - GRABADORA_S3_ACCESS_KEY=minioadmin
      - GRABADORA_S3_SECRET_KEY=minioadmin
      - GRABADORA_S3_BUCKET_AUDIO=audio
      - GRABADORA_S3_BUCKET_TRANSCRIPTS=transcripts
    volumes:
      - ./:/app
    depends_on:
      - redis
      - db
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grabadora
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./deploy/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
